name: CI
on: 
  workflow_dispatch:
 
jobs:
 node-server-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         Port: [10016, 10017, 10018, 10019, 10020]
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
        name: Server build start on Port ${{matrix.Port}}
      - name: Run the Server build process
        uses: addnab/docker-run-action@v3
        with:
            image: ${{ secrets.IMAGE }}
            run: |
                echo gas
                sleep 1m

 server-control:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         Port: [10016, 10017, 10018, 10019, 10020]
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
        name: Server build start on Port ${{matrix.Port}}
      - name: Run the Server build process
        uses: addnab/docker-run-action@v3
        with:
            image: ${{ secrets.IMAGE }}
            run: |
                echo gas
                sleep 1m

 clean-server:
    runs-on: ubuntu-latest
    if: always()
    needs: [server-control, node-server-build]
    timeout-minutes: 360
    steps:
      - name: Server Clean
        uses: addnab/docker-run-action@v3
        with:
            image: ${{ secrets.CRIMAGE }}
            run: |
                echo gas
                sleep 1m
